version: "2.1"
services:
  mysql-knimer:
    image: mysql:8.0.19
    container_name: mysql-knimer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpsw
      MYSQL_DATABASE: knimer
      MYSQL_USER: knimer
      MYSQL_PASSWORD: knimerpsw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  knimer:
    build: .
    restart: on-failure
    ports:
      - 8081:8081
    expose:
      - "8081"
    links:
      - "mysql-knimer:database"
    depends_on:
      mysql-knimer:
        condition: service_healthy



