version: "3.3"
services:
  mysql-keyclock:
    container_name: mysql-keyclock
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpsw
      MYSQL_DATABASE: keycloak
      MYSQL_PASSWORD: keypsw
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: saman
      DB_VENDOR: mysql
      DB_ADDR: mysql-keyclock
      DB_USER: keycloak
      DB_PASSWORD: keypsw
      WAIT_HOSTS: mysql-keyclock:3306
    ports:
      - 8080:8080
    expose:
      - "8080"
    links:
      - mysql-keyclock
    depends_on:
      - mysql-keyclock
#networks:
#  default:
#    internal:
#      name: test-1





