version: "2.1"
services:
  mysql-keyclock:
    container_name: mysql-keyclock
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: rootpsw
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keypsw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: saman
      JDBC_PARAMS: "useSSL=false"
      DB_VENDOR: mysql
      DB_ADDR: mysql-keyclock
      DB_SCHEMA: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keypsw
    ports:
      - 8080:8080
    expose:
      - "8080"
    links:
      - mysql-keyclock
    depends_on:
      mysql-keyclock:
        condition: service_healthy
#networks:
#  default:
#    internal:
#      name: test-1





