keycloak:
#  auth-server-url: http://127.0.0.1:8080/auth
  auth-server-url: http://10.251.103.3:8080/auth
  principal-attribute: preferred_username
  public-client: true
  realm: knimer
  resource: knimer-service
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knimer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: snapp
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect